select * from customer

-- Q1. What is the total revenue generated by male vs. female customers?

select gender, SUM(purchase_amount) as revenue
from customer
group by gender

-- Q2. Which customers used a discount but still spent more than the average purchase amount?

select customer_id,purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

-- Q3. Which are the top 5 products with the highest average review rating?

select item_purchased, ROUND(AVG(review_rating),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

select shipping_type,
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type 



-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

select subscription_status, COUNT(customer_id) AS total_customers,
ROUND(AVG(purchase_amount),2) as average_spend, 
SUM(purchase_amount) AS total_revenue
from customer
group by subscription_status
order by total_revenue, average_spend DESC;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT
    Item_Purchased,
    Category,
    -- Calculate the count of discounted purchases for this product
    COUNT(CASE WHEN Discount_Applied = 'Yes' THEN 1 END) AS Discounted_Purchases,
    
    -- Calculate the total number of purchases for this product
    COUNT(*) AS Total_Purchases,
    
    -- Calculate the percentage: (Discounted Purchases / Total Purchases) * 100.0
    ROUND((COUNT(CASE WHEN Discount_Applied = 'Yes' THEN 1 END) * 100.0 / COUNT(*)),2) AS Discount_Rate_Percentage
FROM
    customer 
GROUP BY
    Item_Purchased,
    Category
ORDER BY
    Discount_Rate_Percentage DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

with customer_type as (
select customer_id, previous_purchases,
CASE
	WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer
)
select customer_segment, count(*) as "Number Of Customers"
from customer_type
group by customer_segment    

-- Q8. What are the top 3 most purchased products within each category?

with item_counts as (
select category, item_purchased, COUNT(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) DESC) as item_rank
from customer 
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;



-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status 

-- Q10. What is the revenue contribution of each age group?

select age_group, SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;